#if(!require(newsmap)){install.packages("newsmap")}
if(!require(udpipe)){install.packages('udpipe')}
if(!require(stringr)){install.packages('stringr')}
if(!require(devtools)){install.packages("devtools")}
if(!require(quanteda)){install.packages("quanteda")}
if(!require(caret)){install.packages("caret")}
library(devtools)
if(!require(quanteda.textmodels)){install.packages("quanteda.textmodels")}
if(!require(keras)){install.packages("keras")}
if(!require(quanteda.classifiers)){devtools::install_github("quanteda/quanteda.classifiers")}
library(quanteda.textmodels)
if(!require(cld3)){install.packages("cld3")}
library(udpipe)
library(quanteda.dictionaries)
library(quanteda)
library(caret)
library(stringr)
library(cld3)
if(!require(text2vec)){install.packages("text2vec")}
if(!require(vegan)){install.packages("vegan")}
if(!require(stm)){install.packages("stm")}
library(keras)

install_keras()