if(!require(stringr)){install.packages('stringr')}
if(!require(devtools)){install.packages("devtools")}
if(!require(quanteda)){install.packages("quanteda")}
if(!require(caret)){install.packages("caret")}
if(!require(quanteda.textmodels)){install.packages("quanteda.textmodels")}
library(quanteda.textmodels)
library(quanteda.dictionaries)
library(quanteda)
library(caret)
library(stringr)